// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3SqP08uHLtA264HOwMy0SRt5lpwEdcd8',
    appId: '1:370308238427:web:8524f1df88a405879bc37e',
    messagingSenderId: '370308238427',
    projectId: 'reddit-clone-744fe',
    authDomain: 'reddit-clone-744fe.firebaseapp.com',
    storageBucket: 'reddit-clone-744fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHX3v7DoPMvb0QWhZBdxP2PX3_ZzIWio',
    appId: '1:370308238427:android:1114fabbe89b0e869bc37e',
    messagingSenderId: '370308238427',
    projectId: 'reddit-clone-744fe',
    storageBucket: 'reddit-clone-744fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmiwI_MYkWt27hg9xJzjbCe5ElhN79Jzs',
    appId: '1:370308238427:ios:42a0d8fb5806f7ef9bc37e',
    messagingSenderId: '370308238427',
    projectId: 'reddit-clone-744fe',
    storageBucket: 'reddit-clone-744fe.appspot.com',
    iosClientId: '370308238427-evloafabiil5jq2687hr11shtig3pqse.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmiwI_MYkWt27hg9xJzjbCe5ElhN79Jzs',
    appId: '1:370308238427:ios:42a0d8fb5806f7ef9bc37e',
    messagingSenderId: '370308238427',
    projectId: 'reddit-clone-744fe',
    storageBucket: 'reddit-clone-744fe.appspot.com',
    iosClientId: '370308238427-evloafabiil5jq2687hr11shtig3pqse.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
